title: 4754 Raven Run
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.internet_ping
      - entity: binary_sensor.updater
      - entity: binary_sensor.living_room_sensor_motion
      - entity: person.croix
      - entity: person.nathaniel_crutcher
      - entity: person.vivien
      - entity: sensor.living_room_sensor_light_level
      - entity: sensor.living_room_sensor_temperature
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - light.custom_group_for_lights
          - light.master
          - light.group_for_wakeup
          - light.living_room_tv
          - light.group_for_wakeup_2
          - light.vivien
          - light.group_for_wakeup_3
          - light.croix
          - light.breakfast
          - light.living_room
          - light.living_room_strip
          - light.vivien_amb_1
          - light.croix_color_1
          - light.breakfast_color_1
          - light.vivien_color_1
          - light.vivien_amb_2
          - light.breakfast_color_2
          - light.master_amb_2
          - light.master_color_1
          - light.living_color_2
          - light.croix_amb_1
          - light.croix_amb_2
          - light.master_amb_1
          - light.living_white_1
          - light.breakfast_color_3
          - light.living_color_1
        title: Light
      - type: media-control
        entity: media_player.samsung_tv
      - type: media-control
        entity: media_player.living_room_speaker
      - type: media-control
        entity: media_player.home_group
      - type: media-control
        entity: media_player.master_bedroom_speaker
      - type: media-control
        entity: media_player.croix_s_room_speaker
      - type: weather-forecast
        entity: weather.raven_run
      - type: gauge
        entity: sensor.living_room_sensor_light_level
      - type: history-graph
        title: "Living Room Temperature"
        refresh_interval: 60
        hours_to_show: 24
        entities:
          - entity: sensor.living_room_sensor_temperature

